/**
 * Команда `zarya` в чужом терминале — чистая часть.
 *
 * inc-30 научил Зарю принимать папку из командной строки, но набрать `zarya .`
 * было негде: установщик кладёт `Zarya.exe` и PATH не трогает. Здесь всё, что
 * можно решить без диска и без реестра — содержимое шимов и правка строки PATH.
 *
 * Отдельным файлом, потому что цена ошибки несимметрична: не дописать пункт —
 * команда не появилась, а испортить чужой PATH — человек остаётся без половины
 * своих программ и не понимает, почему. Такое проверяется юнитами, а не глазами
 * на живой машине, где неудачный прогон стоит рабочего дня.
 */

/** Имя команды. Одно на все места, чтобы шим и поиск не разошлись. */
export const CLI_NAME = 'zarya'

/**
 * Приведение пути к сравнимому виду.
 *
 * Windows не различает регистр, а `C:\Bin` и `c:\bin\` — одна и та же папка.
 * Сравнивать их как строки значило бы при каждом нажатии дописывать в PATH
 * ещё один пункт к уже имеющемуся.
 *
 * Хвостовой разделитель снимаем, КРОМЕ корня диска: `C:\` без слэша это `C:`,
 * а это не папка, а «текущий каталог диска C» — совсем другое место.
 */
export function normPath(p: string): string {
  const t = p.trim().replace(/[\\/]+$/, '')
  // `C:` после срезки — был корень диска.
  return (/^[a-zA-Z]:$/.test(t) ? t + '\\' : t).toLowerCase()
}

/** Есть ли папка среди пунктов PATH. */
export function pathHas(pathValue: string, dir: string): boolean {
  const want = normPath(dir)
  return pathValue.split(';').some((p) => p.trim() !== '' && normPath(p) === want)
}

/**
 * Дописать папку в конец PATH. `null` — менять нечего, она уже там.
 *
 * ПРАВКА МИНИМАЛЬНАЯ: остальные пункты не переписываются и не «чистятся».
 * Пустой пункт `;;` посреди чужого PATH — дело хозяина, а не наше; вычистить
 * его заодно значило бы менять то, о чём не просили.
 *
 * В КОНЕЦ, а не в начало: наша папка не должна перебивать программы, которые
 * человек поставил раньше нас.
 */
export function pathAdd(pathValue: string, dir: string): string | null {
  if (pathHas(pathValue, dir)) return null
  const base = pathValue.trim()
  if (!base) return dir
  return base.endsWith(';') ? base + dir : base + ';' + dir
}

/** Убрать папку из PATH. `null` — её там и не было. */
export function pathRemove(pathValue: string, dir: string): string | null {
  if (!pathHas(pathValue, dir)) return null
  const want = normPath(dir)
  return pathValue
    .split(';')
    .filter((p) => p.trim() === '' || normPath(p) !== want)
    .join(';')
    .replace(/;+$/, '')
}

/**
 * Файлы, которые Windows перебрала бы, ища команду по имени.
 *
 * Порядок ровно тот же, что у оболочки: папки PATH слева направо, внутри каждой
 * — расширения из PATHEXT. Нужен он затем, чтобы ответить на вопрос, которого
 * не задаёт ни один установщик: «а точно ли `zarya` — это МЫ?» Чужая программа
 * с таким же именем в папке левее выигрывает, и кнопка «установлено» без этой
 * проверки соврала бы.
 */
export function resolveCandidates(name: string, pathValue: string, pathext: string): string[] {
  const exts = pathext
    .split(';')
    .map((e) => e.trim())
    .filter(Boolean)
  const out: string[] = []
  for (const raw of pathValue.split(';')) {
    const dir = raw.trim()
    if (!dir) continue
    const base = dir.replace(/[\\/]+$/, '')
    for (const ext of exts) out.push(`${base}\\${name}${ext}`)
  }
  return out
}

/**
 * Экранирование для `set "X=…"` в batch-файле: только процент и опасен.
 * В путях он почти не встречается, но «почти» — это не «никогда».
 */
function cmdEscape(value: string): string {
  return value.replace(/%/g, '%%')
}

/** Экранирование для одинарных кавычек sh. */
function shEscape(value: string): string {
  return value.replace(/'/g, `'\\''`)
}

/**
 * Отчего сообщения внутри шимов — по-английски.
 *
 * Шим печатает их в ЧУЖОМ терминале, кодовую страницу которого мы не знаем.
 * Русский текст в `.cmd` там превратится в мусор, а `chcp` ради одной строки
 * переключит кодировку всей чужой сессии и оставит её так. Английская фраза с
 * путём понятна и не портит терминал.
 */

/**
 * `zarya.cmd` — для cmd и PowerShell.
 *
 * `prefix` не пуст только в разработке: там exe — это `electron.exe`, и первым
 * аргументом ему нужен сам скрипт. Собранному приложению аргументы не нужны.
 *
 * Проверка `if not exist` — про случай, когда Зарю удалили, не сняв команду:
 * человек получает имя папки, которую надо убрать из PATH, вместо загадочного
 * «не является внутренней или внешней командой».
 */
export function cmdShim(exe: string, prefix: readonly string[], binDir: string): string {
  const args = prefix.map((a) => ` "${cmdEscape(a)}"`).join('')
  return [
    '@echo off',
    'rem Zarya CLI shim. Generated by the app — edits are overwritten on next launch.',
    'setlocal',
    `set "ZARYA_EXE=${cmdEscape(exe)}"`,
    'if not exist "%ZARYA_EXE%" goto :gone',
    `"%ZARYA_EXE%"${args} %*`,
    'exit /b %errorlevel%',
    ':gone',
    'echo Zarya is no longer installed at:',
    'echo   %ZARYA_EXE%',
    'echo Remove this folder from your PATH:',
    `echo   ${cmdEscape(binDir)}`,
    'exit /b 9009',
    ''
  ].join('\r\n')
}

/**
 * `zarya` — тот же шим для git-bash и MSYS.
 *
 * Нужен потому, что bash из MSYS не знает про PATHEXT: он ищет `zarya` и
 * `zarya.exe`, но не `zarya.cmd`. Только с одним `.cmd` человек в git-bash
 * получил бы «command not found» при установленной команде. Так же устроен
 * npm — `npm` и `npm.cmd` лежат рядом.
 *
 * Запуск в фоне, а не `exec`: bash ждёт дочерний процесс независимо от того,
 * оконная программа или нет, и терминал стоял бы, пока открыта Заря.
 */
export function shShim(exe: string, prefix: readonly string[], binDir: string): string {
  const args = prefix.map((a) => ` '${shEscape(a)}'`).join('')
  return [
    '#!/bin/sh',
    '# Zarya CLI shim. Generated by the app — edits are overwritten on next launch.',
    `ZARYA_EXE='${shEscape(exe)}'`,
    'if command -v cygpath >/dev/null 2>&1; then',
    '  ZARYA_EXE=$(cygpath -u "$ZARYA_EXE")',
    /*
     * Проверка существования — ТОЛЬКО когда путь удалось привести к виду,
     * понятному sh. Иначе `[ -f "C:\…" ]` не найдёт установленную Зарю (для sh
     * это имя файла с обратными слэшами), и шим уверенно соврёт «её удалили» —
     * ровно тот сорт вранья, ради которого проверка и заводилась.
     */
    '  if [ ! -f "$ZARYA_EXE" ]; then',
    '    echo "Zarya is no longer installed at:" >&2',
    '    echo "  $ZARYA_EXE" >&2',
    '    echo "Remove this folder from your PATH:" >&2',
    `    echo "  ${shEscape(binDir)}" >&2`,
    '    exit 127',
    '  fi',
    'fi',
    `"$ZARYA_EXE"${args} "$@" >/dev/null 2>&1 &`,
    'exit 0',
    ''
  ].join('\n')
}
